GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoia3lsZSIsImlhdCI6MTY5MDExNjgzMn0.nijYqVwSVA6GUxZC4pIkKOXw5ri7NbvBF53wkLyDCFI

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "kyle"
}